#ifndef TOMATOLIB_H
#define TOMATOLIB_H

typedef enum tomato_syscall_kind {
	SYSCALL_TERM_WRITE = 1,
	SYSCALL_TERM_CLEAR,
	SYSCALL_TERM_SET_TEXT_COLOR,
	SYSCALL_TERM_SET_BACKGROUND_COLOR,
	SYSCALL_TERM_GET_TEXT_COLOR,
	SYSCALL_TERM_GET_BACKGROUND_COLOR,
	SYSCALL_TERM_SET_CURSOR_POS,
	SYSCALL_TERM_GET_CURSOR_X,
	SYSCALL_TERM_GET_CURSOR_Y,
	SYSCALL_TERM_SCROLL,
	SYSCALL_TERM_WIDTH,
	SYSCALL_TERM_HEIGHT,
	SYSCALL_TERM_CLEAR_LINE,

	SYSCALL_HEAP_ALLOCATE,
	SYSCALL_HEAP_REALLOCATE,
	SYSCALL_HEAP_FREE,
	SYSCALL_HEAP_GET_PTR_SIZE,
	SYSCALL_HEAP_GET_USED_SIZE
} tomato_syscall_kind_t;
